name: push_to_prod
on: 
  workflow_dispatch:

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v3.1.0
      with:
        python-version: '3.8'
  
    - name: Check out dev repo
      uses: actions/checkout@v2.3.4
      with:
        path: dev
        persist-credentials: false

    - name: Login to DockerHub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Publish Addon Image
      uses: home-assistant/builder@master
      with:
        args: |
          --all \
          --target dev/hassio-google-drive-backup
